# Generated by Django 5.2.14 on 2026-05-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='手机号'),
        ),
    ]
