# Generated by Django 5.2.14 on 2026-05-29 02:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tracking_number', models.CharField(max_length=100, verbose_name='快递单号')),
                ('seller_order_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='商家订单号')),
                ('scheme_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='计划单号')),
                ('image_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='单据图片路径')),
                ('ocr_status', models.CharField(choices=[('pending', '识别中'), ('confirmed', '已确认'), ('failed', '识别失败')], default='confirmed', max_length=20, verbose_name='OCR状态')),
                ('is_settled', models.BooleanField(default=False, verbose_name='是否结清')),
                ('created_at', models.DateTimeField(verbose_name='创建时间')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '入库单',
                'verbose_name_plural': '入库单',
                'unique_together': {('shop', 'tracking_number')},
            },
        ),
        migrations.CreateModel(
            name='InboundItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product_code', models.CharField(max_length=100, verbose_name='商品编码')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('quantity', models.IntegerField(verbose_name='入库数量')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='采购价')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='零售价')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop', verbose_name='所属店铺')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inboundreceipt', verbose_name='入库单')),
            ],
            options={
                'verbose_name': '入库商品明细',
                'verbose_name_plural': '入库商品明细',
            },
        ),
        migrations.CreateModel(
            name='OutboundOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('logistics_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='物流单号')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(verbose_name='创建时间')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '出库单',
                'verbose_name_plural': '出库单',
            },
        ),
        migrations.CreateModel(
            name='OutboundItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product_code', models.CharField(max_length=100, verbose_name='商品编码')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('quantity', models.IntegerField(verbose_name='出库数量')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='销售价')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop', verbose_name='所属店铺')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.outboundorder', verbose_name='出库单')),
            ],
            options={
                'verbose_name': '出库商品明细',
                'verbose_name_plural': '出库商品明细',
            },
        ),
        migrations.CreateModel(
            name='OutboundAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image_path', models.CharField(max_length=500, verbose_name='图片文件路径')),
                ('created_at', models.DateTimeField(verbose_name='创建时间')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop', verbose_name='所属店铺')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.outboundorder', verbose_name='出库单')),
            ],
            options={
                'verbose_name': '出库图片附件',
                'verbose_name_plural': '出库图片附件',
            },
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product_code', models.CharField(max_length=100, verbose_name='商品编码')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('delta', models.IntegerField(verbose_name='库存变动量')),
                ('reason', models.CharField(choices=[('inbound', '扫码入库'), ('outbound', '出库出货'), ('adjustment', '库存校准')], max_length=30, verbose_name='变动原因')),
                ('source_id', models.CharField(max_length=100, verbose_name='关联单据ID')),
                ('created_at', models.DateTimeField(verbose_name='创建时间')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '库存流水账本',
                'verbose_name_plural': '库存流水账本',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=100, verbose_name='商品编码')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('default_purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='默认采购价')),
                ('default_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='默认零售价')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'unique_together': {('shop', 'code')},
            },
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product_code', models.CharField(max_length=100, verbose_name='商品编码')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('quantity', models.IntegerField(default=0, verbose_name='当前库存量')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '当前库存状态',
                'verbose_name_plural': '当前库存状态',
                'unique_together': {('shop', 'product_code')},
            },
        ),
    ]
