# Generated by Django 5.2.14 on 2026-05-29 04:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('CREATE', '新增'), ('UPDATE', '修改'), ('DELETE', '删除')], max_length=20, verbose_name='操作类型')),
                ('tracking_number', models.CharField(max_length=100, verbose_name='快递单号')),
                ('detail', models.TextField(verbose_name='变更详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop', verbose_name='所属店铺')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '入库单操作日志',
                'verbose_name_plural': '入库单操作日志',
            },
        ),
    ]
